Repository ergonode/frontend, pull requests merged in 2021-08, with the labels that each got.

#1008 Add support for preview file
  modules/@ergonode/media/src/components/Forms/ResourceForm.vue
  modules/@ergonode/media/src/components/Grids/MediaGrid.vue
  modules/@ergonode/media/src/components/Inputs/FilePreview.vue
  modules/@ergonode/media/src/config/extends.js
  modules/@ergonode/media/src/config/imports.js
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridImagePreviewCollectionCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridImagePreviewDataCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Presentation/GridFilePresentationCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Columns/GridImagePreviewColumn.vue
  modules/@ergonode/media/src/store/media/actions.js
  modules/@ergonode/media/src/store/media/state.js
  modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
Labels: feature

#1009 Improve copy and support for not chosen binding attributes
  modules/@ergonode/products/src/extends/components/Modals/AddBindingAttributesModalForm.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Product, feature

#1011 Sync workflow transition models
  modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
  modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerEditStatusLink.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
  modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
  modules/@ergonode/workflow/src/components/Tabs/WorkflowDesignerTab.vue
  modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
  modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
  modules/@ergonode/workflow/src/models/workflowDesigner/index.js
  modules/@ergonode/workflow/src/store/workflow/actions.js
Labels: bug

#1013 Add download file / img support
  modules/@ergonode/category-trees/src/components/TreeDesigners/CategoryTreeDesigner.vue
  modules/@ergonode/category-trees/src/locales/en_GB.json
  modules/@ergonode/category-trees/src/locales/pl_PL.json
  modules/@ergonode/collections/src/extends/product/components/ExpandingCollection/ExpandingCollection.vue
  modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesigner.vue
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/media/src/components/Forms/ResourceForm.vue
  modules/@ergonode/media/src/components/Inputs/FilePreview.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridImagePreviewCollectionCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Presentation/GridFilePresentationCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Columns/GridImagePreviewColumn.vue
  modules/@ergonode/media/src/locales/en_GB.json
  modules/@ergonode/media/src/locales/pl_PL.json
Labels: bug

#1017 Downloaded resource with correct extension
  modules/@ergonode/media/src/components/Inputs/FilePreview.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
Labels: bug

#1018 Replace download resource url
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
Labels: bug

#1019 Add missing extended image preview cells
  modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
Labels: bug

#1020 e2e auth tests
  cypress/integration/00:auth/1:login.feature
  cypress/integration/00:auth/1:login/index.test.js
  cypress/integration/00:auth/2:help.feature
  cypress/integration/00:auth/2:help/index.test.js
  cypress/integration/00:auth/3:password.feature
  cypress/integration/00:auth/3:password/index.test.js
  modules/@ergonode/authentication/src/components/Forms/LoginCredentialsForm.vue
  modules/@ergonode/authentication/src/components/Forms/LoginForm.vue
  modules/@ergonode/authentication/src/components/Forms/LoginHelpForm.vue
  modules/@ergonode/authentication/src/components/Forms/PasswordRecoveryForm.vue
  modules/@ergonode/authentication/src/components/Layout/Login.vue
  package-lock.json
  package.json
Labels: tests

#1022 Er 1460/batch actions sidebar
  jest.config.js
  modules/@ergonode/core/src/components/FlashMessages/__tests__/FlashMessage.test.js
  modules/@ergonode/core/src/components/ToolBar/__tests__/ToolBarUserButton.test.js
  modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
  modules/@ergonode/product-batch-actions/src/components/VerticalTabs/AttributesVerticalTab.vue
  modules/@ergonode/products/src/components/Progress/__tests__/ProductCompleteness.test.js
  modules/@ergonode/ui/src/components/AdvancedFilters/Dropdown/AdvancedFilterDropdown.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/__tests__/AdvancedFilterShowOnly.test.js
  modules/@ergonode/ui/src/components/Alert/__tests__/Alert.test.js
  modules/@ergonode/ui/src/components/Badges/__tests__/InformationBadge.test.js
  modules/@ergonode/ui/src/components/Badges/__tests__/NumericBadge.test.js
  modules/@ergonode/ui/src/components/Badges/__tests__/PointBadge.test.js
  modules/@ergonode/ui/src/components/Designer/__tests__/Designer.test.js
  modules/@ergonode/ui/src/components/Designer/__tests__/DesignerGhostItem.test.js
  modules/@ergonode/ui/src/components/Layout/Errors/__tests__/404.test.js
  modules/@ergonode/ui/src/components/Layout/Errors/__tests__/__snapshots__/404.test.js.snap
  modules/@ergonode/ui/src/components/MenuList/__tests__/MenuListElement.test.js
  modules/@ergonode/ui/src/components/Resizer/Resizer.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
  modules/@ergonode/ui/src/components/TitleBar/__tests__/TitleBar.test.js
  modules/@ergonode/ui/src/components/TitleBar/__tests__/TitleBarBreadcrumb.test.js
  modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBar.test.js.snap
  modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBarBreadcrumb.test.js.snap
  modules/@ergonode/ui/src/components/ToolBar/__tests__/ToolBarSelectButton.test.js
Labels: bug

#1023 Add missing affected by values
  modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerMultiSelectItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNumericItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerSelectItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerTextItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerUnitItemParameter.vue
  modules/@ergonode/conditions/src/models/conditionSetMapper.js
Labels: bug

#1027 designer button fix
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
  modules/@ergonode/ui/src/components/ActionIconButton/ActionIconButton.vue
  modules/@ergonode/ui/src/components/Designer/DesignerItem.vue
  modules/@ergonode/ui/src/components/Designer/DesignerItemDescription.vue
  modules/@ergonode/ui/src/plugins/global-component-loader.js
Labels: bug

#1029 attribute types translations
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/attributes/src/extends/attribute/components/SideBars/AttributeSideBarElement.vue
  modules/@ergonode/attributes/src/locales/en_GB.json
  modules/@ergonode/attributes/src/locales/pl_PL.json
  modules/@ergonode/core/src/store/dictionaries/actions.js
  modules/@ergonode/product-templates/src/components/SideBars/WidgetSideBarElement.vue
  modules/@ergonode/product-templates/src/components/TemplateDesigner/ProductDesigner/AttributeElementContent.vue
  modules/@ergonode/product-templates/src/components/TemplateDesigner/ProductDesigner/SectionElementContent.vue
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/product-templates/src/pages/product-templates/_template/_id.vue
Labels: bug, Template designer, Attribute

#1032 Rename default product columns
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
Labels: feature

#1036 Add media e2e
  cypress/fixtures/files/avatar.png
  cypress/fixtures/files/not_supported_file.log
  cypress/fixtures/files/supported_file1.jpg
  cypress/fixtures/files/supported_file2.jpg
  cypress/fixtures/files/supported_file3.jpg
  cypress/integration/02:attributes/1:create.feature
  cypress/integration/11:workflow/transitions/1:create/index.test.js
  cypress/integration/12:units/3:update.feature
  cypress/integration/12:units/4:delete.feature
  cypress/integration/13:media/1:upload.feature
  cypress/integration/13:media/1:upload/index.test.js
  cypress/integration/13:media/2:read.feature
  cypress/integration/13:media/2:read/index.test.js
  cypress/integration/13:media/3:update.feature
  cypress/integration/13:media/3:update/index.test.js
  cypress/integration/13:media/4:delete.feature
  cypress/integration/13:media/4:delete/index.test.js
  cypress/integration/common/actions.test.js
  cypress/integration/common/inputs.test.js
  cypress/integration/common/navigation.test.js
  cypress/models/navigation.js
  cypress/support/commands.js
  modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
  modules/@ergonode/media/src/components/Buttons/RemoveResourceButton.vue
  modules/@ergonode/media/src/components/Buttons/UploadResourcesButton.vue
  modules/@ergonode/media/src/components/Forms/ResourceForm.vue
  modules/@ergonode/media/src/components/Forms/ResourceTranslationForm.vue
  modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
  modules/@ergonode/media/src/store/media/actions.js
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Header/GridHeaderCell.vue
  modules/@ergonode/ui/src/components/Modal/ModalTabBar.vue
  package-lock.json
  package.json
Labels: tests, feature

#1038 Fixed an empty record for advanced date type filter
  CHANGELOG.md
  modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterDateContent.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateType.vue
Labels: bug

#1039 Fixed an empty record for advanced date type filter
  CHANGELOG.md
  modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterDateContent.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateType.vue
Labels: bug

#1042 Fixed an empty record for advanced date type filter
  CHANGELOG.md
  modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterDateContent.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateType.vue
Labels: bug

#1041 Fixed too long filename for uploaded resource
  CHANGELOG.md
  modules/@ergonode/ui/src/components/UploadFileList/UploadFileListElement.vue
Labels: bug

#1047 Add wrap value option to select input kind
  modules/@ergonode/attribute-groups/src/components/Autocompletes/AttributeGroupsAutocomplete.vue
  modules/@ergonode/attributes/src/components/Autocompletes/AttributesAutocomplete.vue
  modules/@ergonode/collections/src/components/Autocompletes/CollectionTypesAutocomplete.vue
  modules/@ergonode/product-templates/src/components/Autocompletes/ProductTemplatesAutocomplete.vue
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
  modules/@ergonode/roles/src/components/Autocompletes/RolesAutocomplete.vue
  modules/@ergonode/segments/src/components/Autocompletes/SegmentsAutocomplete.vue
  modules/@ergonode/ui/src/components/Autocomplete/Autocomplete.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridMultiSelectEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridMultiSelectEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridSelectEditCell.vue
  modules/@ergonode/ui/src/components/Input/InputSelectValue.vue
  modules/@ergonode/ui/src/components/Input/InputUnderlineStyle.vue
  modules/@ergonode/ui/src/components/Select/Select.vue
Labels: UI Components, feature
