Repository ergonode/frontend, pull requests merged in 2021-12, with the labels that each got.

#1148 Rewritten algorithm for saving attribute options
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValues.vue
  modules/@ergonode/attributes/src/extends/attribute/methods/helpers.js
  modules/@ergonode/attributes/src/extends/attribute/methods/index.js
  modules/@ergonode/attributes/src/extends/attribute/store/actions.js
  modules/@ergonode/attributes/src/extends/attribute/store/getters.js
  modules/@ergonode/attributes/src/extends/attribute/store/index.js
  modules/@ergonode/attributes/src/extends/attribute/store/mutations.js
  modules/@ergonode/attributes/src/extends/attribute/store/state.js
  modules/@ergonode/core/src/models/__tests__/arrayWrapper.test.js
  modules/@ergonode/core/src/models/arrayWrapper.js
  modules/@ergonode/ui/src/components/Form/Section/FormListSection.vue
Labels: feature

#1156 Er 1885/workflow routing change
  UPGRADE-1.3.md
  cypress/integration/11:workflow/status/1:create.feature
  cypress/integration/11:workflow/status/2:read.feature
  cypress/integration/11:workflow/status/3:update.feature
  cypress/integration/11:workflow/status/4:delete.feature
  cypress/integration/11:workflow/transitions/1:create.feature
  cypress/integration/11:workflow/transitions/2:read.feature
  cypress/integration/11:workflow/transitions/3:update.feature
  cypress/integration/11:workflow/transitions/4:delete.feature
  modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
  modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionConditionDesignerButton.vue
  modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
  modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionGeneralTab.vue
  modules/@ergonode/workflow/src/config/routes.js
  modules/@ergonode/workflow/src/pages/workflow/_status/_id.vue
  modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
  modules/@ergonode/workflow/src/services/index.js
  modules/@ergonode/workflow/src/store/workflow/actions.js
  package-lock.json
  package.json
Labels: bug, Workflow

#1160 Er 1883/extend settings
  modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesigner.vue
  modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesignerItem.vue
  modules/@ergonode/roles/src/config/extends.js
  modules/@ergonode/roles/src/config/imports.js
  modules/@ergonode/roles/src/extends/workflow/components/Forms/WorkflowTransitionFormRole.vue
  modules/@ergonode/roles/src/extends/workflow/methods/index.js
  modules/@ergonode/roles/src/extends/workflow/store/index.js
  modules/@ergonode/roles/src/extends/workflow/store/state.js
  modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
Labels: bug

#1158 Feature/attribute option sorting
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/attributes/src/defaults/index.js
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValue.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValues.vue
  modules/@ergonode/attributes/src/extends/attribute/methods/helpers.js
  modules/@ergonode/attributes/src/extends/attribute/methods/index.js
  modules/@ergonode/attributes/src/extends/attribute/services/index.js
  modules/@ergonode/attributes/src/extends/attribute/store/actions.js
  modules/@ergonode/attributes/src/extends/attribute/store/mutations.js
  modules/@ergonode/attributes/src/extends/attribute/store/state.js
  modules/@ergonode/attributes/src/services/index.js
  modules/@ergonode/core/src/models/__tests__/arrayWrapper.test.js
  modules/@ergonode/core/src/models/arrayWrapper.js
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormGhostItem.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
  modules/@ergonode/ui/src/components/Form/Section/FormListSection.vue
Labels: Attribute, feature

#1162 Display code when translation not defined
  modules/@ergonode/products/src/components/Buttons/ProductWorkflowActionButton.vue
Labels: bug

#1163 Er 1881/update workflow
  modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
  modules/@ergonode/workflow/src/store/workflow/actions.js
  modules/@ergonode/workflow/src/store/workflow/state.js
Labels: bug

#1164 Release 1.2.1
  CHANGELOG.md
  lerna.json
  modules/@ergonode/activity-logs/package.json
  modules/@ergonode/attribute-groups/package.json
  modules/@ergonode/attributes/package.json
  modules/@ergonode/authentication/package.json
  modules/@ergonode/batch-actions/package.json
  modules/@ergonode/categories/package.json
  modules/@ergonode/category-trees/package.json
  modules/@ergonode/channels/package.json
  modules/@ergonode/collections/package.json
  modules/@ergonode/comments/package.json
  modules/@ergonode/conditions/package.json
  modules/@ergonode/core/package.json
  modules/@ergonode/dashboard/package.json
  modules/@ergonode/import/package.json
  modules/@ergonode/media/package.json
  modules/@ergonode/notifications/package.json
  modules/@ergonode/product-batch-actions/package.json
  modules/@ergonode/product-statuses/package.json
  modules/@ergonode/product-templates/package.json
  modules/@ergonode/products-comments/package.json
  modules/@ergonode/products/package.json
  modules/@ergonode/roles/package.json
  modules/@ergonode/segments/package.json
  modules/@ergonode/status-transitions/package.json
  modules/@ergonode/ui/package.json
  modules/@ergonode/users/package.json
  modules/@ergonode/workflow/package.json
  package.json
Labels: release

#1168 feat(workflow): Add dragstart for status header
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDraggableHeaderLayerCell.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
Labels: Workflow, feature

#1169 bugfix: status default id
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowStatusButton.vue
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
  modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
  modules/@ergonode/workflow/src/store/workflow/actions.js
Labels: bug

#1170 bugfix: refresh workflow when add status
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Labels: bug, Workflow

#1175 bugfix: workflow menu fix
  modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarElement.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Labels: bug, Workflow

#1174 Attribute group e2e fix
  CHANGELOG.md
  cypress/integration/01:attributeGroups/3:update.feature
  cypress/integration/13:media/1:upload/index.test.js
Labels: bug, tests
