Repository ergonode/frontend, pull requests merged in 2021-03, with the labels that each got.

#751 feature(batch-actions): add support for madia attributes
  modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeFileFormField.vue
  modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeGalleryFormField.vue
  modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeImageFormField.vue
Labels: Batch actions

#753 bugfix: fix scheduler, fix select type on batch-action
  modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
  modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
  modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
  modules/@ergonode/ui/src/components/DatePicker/DatePickerContent.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
Labels: Accepted, Batch actions, Channels, In Progress, bug

#752 feature(batch-actions): add row count before actions
  modules/@ergonode/batch-actions/src/models/paramsSerializer.js
  modules/@ergonode/batch-actions/src/services/index.js
  modules/@ergonode/products-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
  modules/@ergonode/products-batch-actions/src/components/Buttons/UpdateProductsButton.vue
  modules/@ergonode/products-batch-actions/src/components/Modals/UpdateProductsModal.vue
  modules/@ergonode/products-batch-actions/src/locales/en_GB.json
  modules/@ergonode/products-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/products-batch-actions/src/services/index.js
Labels: Accepted, Batch actions, In Progress, feature

#758 feature(batch-actions): filter attribute by templates
  modules/@ergonode/products-batch-actions/src/components/SideBars/AttributesSideBar.vue
Labels: Accepted, Batch actions, feature

#759 bugfix(core): i18n fix default language
  modules/@ergonode/core/src/plugins/i18n.js
Labels: Core, bug

#760 Release/1.0.0 rc.1
  CHANGELOG.md
  lerna.json
  modules/@ergonode/activity-logs/package.json
  modules/@ergonode/attributes/package.json
  modules/@ergonode/authentication/package.json
  modules/@ergonode/batch-actions/package.json
  modules/@ergonode/categories/package.json
  modules/@ergonode/category-trees/package.json
  modules/@ergonode/channels/package.json
  modules/@ergonode/collections/package.json
  modules/@ergonode/comments/package.json
  modules/@ergonode/conditions/package.json
  modules/@ergonode/core/package.json
  modules/@ergonode/dashboard/package.json
  modules/@ergonode/import/package.json
  modules/@ergonode/media/package.json
  modules/@ergonode/notifications/package.json
  modules/@ergonode/product-statuses/package.json
  modules/@ergonode/product-templates/package.json
  modules/@ergonode/products-batch-actions/package.json
  modules/@ergonode/products/package.json
  modules/@ergonode/segments/package.json
  modules/@ergonode/status-transitions/package.json
  modules/@ergonode/ui/package.json
  modules/@ergonode/users/package.json
  package.json
Labels: release

#761 hotfix: import error
  modules/@ergonode/products-batch-actions/src/components/Modals/ProductBatchActionDetailsModalGrid.vue
Labels: bug

#764 Batch actions stabilisation
  modules/@ergonode/batch-actions/src/components/BatchActionsListener/BatchActionsListener.vue
  modules/@ergonode/batch-actions/src/config/extends.js
  modules/@ergonode/batch-actions/src/config/imports.js
  modules/@ergonode/batch-actions/src/models/batchActionMapper.js
  modules/@ergonode/batch-actions/src/services/index.js
  modules/@ergonode/batch-actions/src/store/batchAction/actions.js
  modules/@ergonode/batch-actions/src/store/batchAction/index.js
  modules/@ergonode/batch-actions/src/store/batchAction/mutations.js
  modules/@ergonode/batch-actions/src/store/batchAction/state.js
  modules/@ergonode/core/src/models/mappers/gridDataMapper.js
  modules/@ergonode/product-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
  modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
  modules/@ergonode/product-batch-actions/src/components/SideBars/AttributesSideBar.vue
  modules/@ergonode/product-batch-actions/src/components/VerticalTabs/AttributesVerticalTab.vue
  modules/@ergonode/product-batch-actions/src/locales/en_GB.json
  modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/product-batch-actions/src/services/index.js
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/ui/src/components/Grid/Grid.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Action/GridActionCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Action/GridDeleteActionCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Action/GridEditActionCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Action/GridGetActionCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/GridTableCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Header/GridSelectRowHeaderCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridActionColumn.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridColumn.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableDataColumn.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridRowActionColumn.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridSelectRowColumn.vue
  modules/@ergonode/users/src/components/Grid/Layout/Table/Columns/GridLanguageRowCheckColumn.vue
  modules/@ergonode/users/src/components/Grid/Layout/Table/Columns/GridPrivilegeRowCheckColumn.vue
Labels: Batch actions

#765 bugfix(batch-actions): vuex state error
  modules/@ergonode/batch-actions/src/store/batchAction/actions.js
  modules/@ergonode/batch-actions/src/store/batchAction/index.js
  modules/@ergonode/product-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
  modules/@ergonode/product-batch-actions/src/components/Buttons/UpdateProductsButton.vue
  modules/@ergonode/product-batch-actions/src/locales/en_GB.json
  modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Batch actions, bug

#774 Webpack, dependencies update
  modules/@ergonode/products/src/extends/components/BindingAttributes/AddBindingAttributes.vue
  modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttribute.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFiltersRemoveAllButton.vue
  modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarGroup.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Footers/MultiselectDropdownFooter.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Footers/SelectDropdownFooter.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarItem.vue
  modules/@ergonode/ui/src/components/TabBar/VerticalTabBarItem.vue
  modules/@ergonode/ui/src/components/TextField/TextField.vue
  modules/@ergonode/ui/src/components/ToolBar/ToolBarButton.vue
  modules/@ergonode/ui/src/mixins/inputs/associatedLabelMixin.js
  nuxt.config.js
  package-lock.json
  package.json
Labels: Core, bug

#775 Memory leak, webpack config improvement
  modules/@ergonode/ui/src/mixins/inputs/associatedLabelMixin.js
  nuxt.config.js
Labels: Core, bug

#776 Interface translation flashing on page reload
  modules/@ergonode/core/src/plugins/i18n.js
  nuxt.config.js
Labels: Core, bug

#778 Prevent from adding / removing binding attributes
  modules/@ergonode/products/src/extends/components/BindingAttributes/AddBindingAttributes.vue
  modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttribute.vue
  modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttributes.vue
  modules/@ergonode/products/src/extends/components/Grids/AttachedProductVariantsGrid.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Core, feature

#781 bugfix(notification): fetch data
  modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
  modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
  modules/@ergonode/notifications/src/components/NotificationList/NotificationListMenu.vue
Labels: Batch actions, bug

#779 Remove active languages, instead of use languages from tree
  modules/@ergonode/attributes/src/extends/attribute/components/SideBars/AttributesSideBar.vue
  modules/@ergonode/attributes/src/extends/attribute/components/SideBars/SystemAttributesSideBar.vue
  modules/@ergonode/authentication/src/store/authentication/actions.js
  modules/@ergonode/category-trees/src/extends/product/components/SideBars/CategoryTreesSideBar.vue
  modules/@ergonode/core/src/components/Autocompletes/LanguagesAutocomplete.vue
  modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
  modules/@ergonode/core/src/components/Forms/MainSettingsForm.vue
  modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
  modules/@ergonode/core/src/components/SideBars/LanguagesSideBar.vue
  modules/@ergonode/core/src/components/Tabs/MainSettingsTab.vue
  modules/@ergonode/core/src/components/Tabs/TranslationsTab.vue
  modules/@ergonode/core/src/config/imports.js
  modules/@ergonode/core/src/config/routes.js
  modules/@ergonode/core/src/mixins/card/translationCardMixin.js
  modules/@ergonode/core/src/services/language/index.js
  modules/@ergonode/core/src/store/core/actions.js
  modules/@ergonode/core/src/store/core/getters.js
  modules/@ergonode/core/src/store/core/state.js
  modules/@ergonode/core/src/store/initial.js
  modules/@ergonode/product-batch-actions/src/components/SideBars/AttributesSideBar.vue
  modules/@ergonode/product-statuses/src/components/Widgets/StatusesWidget.vue
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/products/src/extends/components/Modals/AddBindingAttributesModalForm.vue
  modules/@ergonode/products/src/pages/catalog/_product/_id.vue
  modules/@ergonode/ui/src/components/List/ListElementTree.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBar.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarItem.vue
  modules/@ergonode/ui/src/components/TabBar/Routing/HorizontalRoutingTabBar.vue
  modules/@ergonode/ui/src/components/TabBar/Routing/HorizontalRoutingTabBarItem.vue
  modules/@ergonode/ui/src/components/TabBar/TabBarItemSlider.vue
  modules/@ergonode/users/src/components/Forms/UserForm.vue
  modules/@ergonode/users/src/components/Grids/UserLanguageRestrictionsGrid.vue
  modules/@ergonode/users/src/store/user/actions.js
  modules/@ergonode/users/src/store/user/state.js
Labels: Core, feature

#787 dosc: new slack link
  .eslintignore
  .github/ISSUE_TEMPLATE/question.md
  .gitignore
  README.md
Labels: documentation

#791 Bugfix/grid status label
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/products/src/extends/components/Grid/Layout/Table/Cells/Presentation/GridLabelPresentationCell.vue
Labels: Core, bug

#792 Add missing clearable props to Select
  modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormSelect.vue
Labels: Core

#795 bugfix: fixes to html validator
  modules/@ergonode/authentication/src/components/Forms/PasswordRecoveryCheckEmail.vue
  modules/@ergonode/core/src/pages/placeholder/index.vue
  modules/@ergonode/dashboard/src/components/Widgets/StatusesWidget.vue
  modules/@ergonode/products/src/extends/components/BindingAttributes/AddBindingAttributes.vue
  modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttribute.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFiltersRemoveAllButton.vue
  modules/@ergonode/ui/src/components/Fab/Fab.vue
  modules/@ergonode/ui/src/components/IconButton/IconButton.vue
  modules/@ergonode/ui/src/components/LinkButton/LinkButton.vue
  modules/@ergonode/ui/src/components/MenuList/MenuListElement.vue
  modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBar.vue
  modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarElement.vue
  modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarGroupElement.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarItem.vue
  modules/@ergonode/ui/src/components/TabBar/VerticalTabBarItem.vue
  modules/@ergonode/ui/src/components/TitleBar/TitleBarBreadcrumb.vue
  modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBarBreadcrumb.test.js.snap
  modules/@ergonode/ui/src/components/ToolBar/ToolBarBreadcrumb.vue
  modules/@ergonode/ui/src/components/ToolBar/ToolBarButton.vue
Labels: bug

#796 feat(core): JSON Schema description support
  modules/@ergonode/ui/src/components/Button/Button.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaForm.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormSelect.vue
  modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormText.vue
Labels: Core, feature

#797 Category tree hidden missing items
  modules/@ergonode/core/src/models/mappers/__tests__/__mocks__/treeDesigner.mock.js
  modules/@ergonode/core/src/models/mappers/__tests__/treeDesignerMapper.test.js
  modules/@ergonode/core/src/models/mappers/treeDesignerMapper.js
  modules/@ergonode/ui/src/components/TreeDesigner/TreeDesigner.vue
Labels: Core, bug
