Repository ergonode/frontend, pull requests merged in 2021-11, with the labels that each got.

#1107 Change DOM virtualization for dropdown lists
  modules/@ergonode/category-trees/src/components/AdvancedFilters/Type/AdvancedFilterCategoryTreeType.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterMultiselectContent.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterSelectContent.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterMultiSelectType.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterNumericType.vue
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterSelectType.vue
  modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
  modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
  modules/@ergonode/ui/src/components/Select/Select.vue
  modules/@ergonode/ui/src/components/SelectList/SelectList.vue
  modules/@ergonode/ui/src/components/SelectList/SelectListElement.vue
  modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordion.vue
  modules/@ergonode/ui/src/plugins/global-component-loader.js
  package-lock.json
  package.json
Labels: Core, feature

#1108 bugfix: fix e2e tests
  cypress/integration/00:auth/1:login/index.test.js
  cypress/integration/00:auth/2:help/index.test.js
  cypress/integration/00:auth/3:password/index.test.js
  cypress/integration/02:attributes/1:create.feature
  cypress/integration/02:attributes/3:update.feature
  cypress/integration/10:users/1:create.feature
  cypress/integration/13:media/1:upload.feature
  cypress/integration/common/navigation.test.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: tests

#1114 feature(attribute): sort attribute options
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
Labels: Attribute

#1110 Add IntersectionObserver polyfill
  modules/@ergonode/ui/src/components/LazyImage/LazyImage.vue
  nuxt.config.js
  package-lock.json
  package.json
Labels: Core, feature

#1111 Correct class position for SelectList
  modules/@ergonode/ui/src/components/SelectList/SelectList.vue
Labels: bug

#1117 Request product completeness on language change
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
Labels: bug

#1115 Positioning Grid editable cells
  modules/@ergonode/core/src/defaults/grid/index.js
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridImagePreviewDataCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridFileEditCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridGalleryEditCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridImageEditCell.vue
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridImagePreviewEditCell.vue
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridLabelDataCell.vue
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridProductRelationEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridDateFilterDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridDateTimeFilterDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridMultiSelectFilterDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridSelectFilterDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridDateDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridDateTimeDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridMultiSelectDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridSelectDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridTextAreaDataCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridEditContentCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridImageEditContentCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridSelectEditContentCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridTextEditContentCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridDateEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridDateTimeEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridMultiSelectEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridNumericEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridSelectEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridTextEditFilterCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridDateEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridDateTimeEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridMultiSelectEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridNumericEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridSelectEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridTextAreaEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridTextEditCell.vue
  modules/@ergonode/ui/src/mixins/grid/gridDataCellMixin.js
  modules/@ergonode/ui/src/mixins/grid/gridDataFilterCellMixin.js
  modules/@ergonode/ui/src/mixins/grid/gridEditCellMixin.js
  modules/@ergonode/ui/src/mixins/grid/gridEditFilterCellMixin.js
  modules/@ergonode/ui/src/plugins/global-component-loader.js
Labels: bug

#1120 Fix attribute option keys validation
  modules/@ergonode/attributes/src/extends/attribute/methods/index.js
Labels: bug

#1121 Product completeness on language change
  modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
Labels: bug, Product

#1122 Er 1819/option states algorithm
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/attributes/src/defaults/index.js
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValue.vue
  modules/@ergonode/attributes/src/extends/attribute/methods/helpers.js
  modules/@ergonode/attributes/src/extends/attribute/methods/index.js
  modules/@ergonode/attributes/src/extends/attribute/services/index.js
  modules/@ergonode/attributes/src/extends/attribute/store/actions.js
  modules/@ergonode/attributes/src/extends/attribute/store/getters.js
  modules/@ergonode/attributes/src/extends/attribute/store/index.js
  modules/@ergonode/attributes/src/extends/attribute/store/mutations.js
  modules/@ergonode/attributes/src/extends/attribute/store/state.js
  modules/@ergonode/attributes/src/services/index.js
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
Labels: Attribute

#1128 Change Sidebar DOM virtualization
  modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
  modules/@ergonode/ui/src/components/SideBar/SideBar.vue
Labels: UI Components, feature

#1125 Add scrollTop to resizing algorithm
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Resizer/GridCellResizer.vue
  modules/@ergonode/ui/src/mixins/grid/gridResizerCellMixin.js
Labels: bug, UI Components

#1127 Add ListLinkElement component
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
  modules/@ergonode/ui/src/components/List/ListLinkElement.vue
  modules/@ergonode/ui/src/plugins/global-component-loader.js
Labels: UI Components, feature

#1123 Add missing updating option translation logic
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValue.vue
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValues.vue
  modules/@ergonode/attributes/src/extends/attribute/store/actions.js
Labels: bug

#1130 Add preview for text, numeric and rte grid editable cells
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridNumericEditCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridTextEditCell.vue
  modules/@ergonode/ui/src/components/Paragraph/Paragraph.vue
  modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
Labels: UI Components, Core, feature

#1132 feat(core): Add remove all relations option
  modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Product, feature

#1134 Add import / channel form errors mappers
  modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
  modules/@ergonode/core/src/models/mappers/errorsMapper.js
  modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
  modules/@ergonode/product-templates/src/components/SideBars/WidgetsSideBar.vue
  modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
  modules/@ergonode/ui/src/components/SideBar/SideBar.vue
Labels: bug

#1140 Allow extended slots to be defined by layout
  modules/@ergonode/core/src/plugins/core.js
  modules/@ergonode/product-batch-actions/src/config/extends.js
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
Labels: Product, feature

#1137 Filter mapping
  modules/@ergonode/core/src/models/mappers/translationsMapper.js
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateTimeType.vue
Labels: bug

#1138 Filter mapping
  modules/@ergonode/core/src/models/mappers/translationsMapper.js
  modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateTimeType.vue
Labels: bug

#1141 Keeping track of drag end for draggable form item
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormGhostItem.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
Labels: bug

#1142 Simplifying manipulating draggable item form
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
Labels: feature

#1143 Mutate item position on drag end
  modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
  modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
Labels: bug

#1147 Remove defined layouts
  CHANGELOG.md
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/category-trees/src/config/extends.js
Labels: feature request
