Repository ergonode/frontend, pull requests merged in 2021-04, with the labels that each got.

#811 bugfix: product extended tabs
  modules/@ergonode/products/src/config/extends.js
Labels: bug

#812 Translation crash
  modules/@ergonode/batch-actions/src/config/extends.js
  modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
Labels: bug

#815 bugfix(batch-action): translation fix
  modules/@ergonode/batch-actions/src/config/extends.js
Labels: bug

#820 Remove legacy modal injection
  modules/@ergonode/activity-logs/src/pages/activity-logs/index.vue
  modules/@ergonode/attribute-groups/src/pages/attribute-groups/index.vue
  modules/@ergonode/attributes/src/pages/attributes/index.vue
  modules/@ergonode/categories/src/pages/categories/index.vue
  modules/@ergonode/category-trees/src/pages/category-trees/index.vue
  modules/@ergonode/channels/src/pages/channels/index.vue
  modules/@ergonode/collections/src/pages/collections/index.vue
  modules/@ergonode/core/src/pages/settings/index.vue
  modules/@ergonode/import/src/pages/imports/index.vue
  modules/@ergonode/media/src/pages/media/index.vue
  modules/@ergonode/product-statuses/src/pages/product-statuses/index.vue
  modules/@ergonode/product-templates/src/pages/product-templates/index.vue
  modules/@ergonode/products/src/pages/catalog/index.vue
  modules/@ergonode/roles/src/pages/roles/index.vue
  modules/@ergonode/segments/src/pages/segments/index.vue
  modules/@ergonode/status-transitions/src/pages/status-transitions/index.vue
  modules/@ergonode/users/src/pages/profile/index.vue
  modules/@ergonode/users/src/pages/users/index.vue
Labels: Core

#818 Migrate CLI dependencies to dev
  package-lock.json
  package.json
Labels: Core

#824 Placeholder position
  modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Labels: Core, bug

#822 Add support for extended header and footer slots
  modules/@ergonode/activity-logs/src/components/Grids/UsersActivityLogsGrid.vue
  modules/@ergonode/attribute-groups/src/components/Grids/AttributeGroupsGrid.vue
  modules/@ergonode/attributes/src/components/Grids/AttributesGrid.vue
  modules/@ergonode/categories/src/components/Grids/CategoriesGrid.vue
  modules/@ergonode/category-trees/src/components/Grids/CategoryTreesGrid.vue
  modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
  modules/@ergonode/channels/src/components/Grids/ChannelsGrid.vue
  modules/@ergonode/channels/src/components/Grids/ExportDetailsGrid.vue
  modules/@ergonode/collections/src/components/Grids/CollectionProductsGrid.vue
  modules/@ergonode/collections/src/components/Grids/CollectionsGrid.vue
  modules/@ergonode/core/src/components/Grids/UnitsGrid.vue
  modules/@ergonode/core/src/config/index.js
  modules/@ergonode/import/src/components/Grids/ImportProfileHistoryGrid.vue
  modules/@ergonode/import/src/components/Grids/ImportProfilesGrid.vue
  modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
  modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
  modules/@ergonode/media/src/components/Grids/MediaGrid.vue
  modules/@ergonode/product-batch-actions/src/components/Grids/ProductBatchActionDetailsGrid.vue
  modules/@ergonode/product-batch-actions/src/config/index.js
  modules/@ergonode/product-statuses/src/components/Grids/ProductStatusesGrid.vue
  modules/@ergonode/product-templates/src/components/Grids/ProductTemplatesGrid.vue
  modules/@ergonode/products/src/components/Grids/ProductHistoryGrid.vue
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/products/src/extends/components/Grids/AttachedProductVariantsGrid.vue
  modules/@ergonode/products/src/extends/components/Grids/AttachedProductsToGroupGrid.vue
  modules/@ergonode/products/src/extends/components/Grids/ProductVariantsToAttachGrid.vue
  modules/@ergonode/products/src/extends/components/Grids/ProductsToAttachForGroupGrid.vue
  modules/@ergonode/roles/src/components/Grids/RolePrivilegesGrid.vue
  modules/@ergonode/roles/src/components/Grids/RolesGrid.vue
  modules/@ergonode/roles/src/components/Grids/UserPrivilegesGrid.vue
  modules/@ergonode/segments/src/components/Grids/SegmentsGrid.vue
  modules/@ergonode/status-transitions/src/components/Grids/TransitionsGrid.vue
  modules/@ergonode/users/src/components/Grids/UserActivityLogsGrid.vue
  modules/@ergonode/users/src/components/Grids/UserLanguageRestrictionsGrid.vue
  modules/@ergonode/users/src/components/Grids/UsersGrid.vue
Labels: Core

#823 Add parsing for multiselect attribute
  modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormMultiSelectField.vue
Labels: Core, bug

#825 Input box shadow
  modules/@ergonode/ui/src/components/TextField/TextField.vue
Labels: UI Components, bug

#826 Add missing draggable form width support
  modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
Labels: UI Components, bug

#827 Prevent notification details preview
  modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
  modules/@ergonode/product-batch-actions/src/components/NotificationLists/Items/NotificationListBatchActionEndedItem.vue
Labels: Core, bug

#828 Status transition translations
  modules/@ergonode/status-transitions/src/components/Buttons/CreateStatusTransitionButton.vue
  modules/@ergonode/status-transitions/src/components/Buttons/RemoveStatusTransitionButton.vue
  modules/@ergonode/status-transitions/src/components/Buttons/UpdateProductStatusConditionDesignerButton.vue
  modules/@ergonode/status-transitions/src/components/DropZones/RemoveConditionDropZone.vue
  modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
  modules/@ergonode/status-transitions/src/components/Grids/TransitionsGrid.vue
  modules/@ergonode/status-transitions/src/components/Modals/CreateStatusTransitionModalForm.vue
  modules/@ergonode/status-transitions/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/status-transitions/src/components/Tabs/TransitionGeneralTab.vue
  modules/@ergonode/status-transitions/src/locales/en_GB.json
  modules/@ergonode/status-transitions/src/locales/pl_PL.json
  modules/@ergonode/status-transitions/src/pages/status-transitions/_transition/_id.vue
  modules/@ergonode/status-transitions/src/pages/status-transitions/index.vue
  modules/@ergonode/status-transitions/src/store/statusTransition/actions.js
Labels: Core

#830 Product interface translations
  modules/@ergonode/products/src/components/Buttons/RemoveProductButton.vue
  modules/@ergonode/products/src/components/Buttons/UpdateProductTemplateButton.vue
  modules/@ergonode/products/src/components/Chart/DoughnutProductsChart.vue
  modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormNoTypeField.vue
  modules/@ergonode/products/src/components/Forms/ProductForm.vue
  modules/@ergonode/products/src/components/Forms/ProductTemplateForm.vue
  modules/@ergonode/products/src/components/Grids/ProductHistoryGrid.vue
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/products/src/components/Modals/CreateProductModalForm.vue
  modules/@ergonode/products/src/components/Modals/RestoreAttributeParentConfirmModal.vue
  modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
  modules/@ergonode/products/src/components/Progress/__tests__/ProductCompleteness.test.js
  modules/@ergonode/products/src/components/Tabs/ProductGeneralTab.vue
  modules/@ergonode/products/src/extends/components/Buttons/AddProductVariantsButton.vue
  modules/@ergonode/products/src/extends/components/Buttons/UpdateProductsAttachmentButton.vue
  modules/@ergonode/products/src/extends/components/Forms/AddProductsBySKUForm.vue
  modules/@ergonode/products/src/extends/components/Forms/Field/ProductAttributeBindingField.vue
  modules/@ergonode/products/src/extends/components/Forms/ProductAttributesBindingForm.vue
  modules/@ergonode/products/src/extends/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
  modules/@ergonode/products/src/extends/components/Grids/AttachedProductsToGroupGrid.vue
  modules/@ergonode/products/src/extends/components/Modals/AddBindingAttributesModalForm.vue
  modules/@ergonode/products/src/extends/components/Modals/AddProductsBySKUModalForm.vue
  modules/@ergonode/products/src/extends/components/Modals/AddProductsFromSegmentModalForm.vue
  modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Core

#829 Segment translations
  modules/@ergonode/segments/src/components/Autocompletes/SegmentsAutocomplete.vue
  modules/@ergonode/segments/src/components/Buttons/CreateSegmentButton.vue
  modules/@ergonode/segments/src/components/Buttons/RemoveSegmentButton.vue
  modules/@ergonode/segments/src/components/Buttons/UpdateSegmentConditionDesignerButton.vue
  modules/@ergonode/segments/src/components/Buttons/UpdateSegmentTranslationButton.vue
  modules/@ergonode/segments/src/components/DropZones/RemoveConditionDropZone.vue
  modules/@ergonode/segments/src/components/Forms/SegmentForm.vue
  modules/@ergonode/segments/src/components/Forms/SegmentTranslationForm.vue
  modules/@ergonode/segments/src/components/Grids/SegmentsGrid.vue
  modules/@ergonode/segments/src/components/Modals/CreateSegmentModalForm.vue
  modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/segments/src/components/Tabs/SegmentGeneralTab.vue
  modules/@ergonode/segments/src/locales/en_GB.json
  modules/@ergonode/segments/src/locales/pl_PL.json
  modules/@ergonode/segments/src/pages/segments/_segment/_id.vue
  modules/@ergonode/segments/src/pages/segments/index.vue
  modules/@ergonode/segments/src/store/segment/actions.js
  modules/@ergonode/ui/src/components/DropZone/DropZone.vue
Labels: Core

#832 Product statuses interface translations
  modules/@ergonode/product-statuses/src/components/Buttons/CreateProductStatusButton.vue
  modules/@ergonode/product-statuses/src/components/Buttons/RemoveProductStatusButton.vue
  modules/@ergonode/product-statuses/src/components/Buttons/UpdateProductStatusTranslationButton.vue
  modules/@ergonode/product-statuses/src/components/Forms/ProductStatusForm.vue
  modules/@ergonode/product-statuses/src/components/Forms/ProductStatusTranslationForm.vue
  modules/@ergonode/product-statuses/src/components/Grids/ProductStatusesGrid.vue
  modules/@ergonode/product-statuses/src/components/Modals/CreateProductStatusModalForm.vue
  modules/@ergonode/product-statuses/src/components/Tabs/ProductStatusGeneralTab.vue
  modules/@ergonode/product-statuses/src/locales/en_GB.json
  modules/@ergonode/product-statuses/src/locales/pl_PL.json
  modules/@ergonode/product-statuses/src/pages/product-statuses/_status/_id.vue
  modules/@ergonode/product-statuses/src/pages/product-statuses/index.vue
  modules/@ergonode/product-statuses/src/store/productStatus/actions.js
Labels: Core

#831 Product template interface translations
  modules/@ergonode/product-templates/src/components/Autocompletes/ProductTemplatesAutocomplete.vue
  modules/@ergonode/product-templates/src/components/Buttons/CreateProductTemplateButton.vue
  modules/@ergonode/product-templates/src/components/Buttons/RemoveProductTemplateButton.vue
  modules/@ergonode/product-templates/src/components/Buttons/UpdateTemplateDesignerButton.vue
  modules/@ergonode/product-templates/src/components/DropZones/RemoveElementDropZone.vue
  modules/@ergonode/product-templates/src/components/Forms/ProductTemplateForm.vue
  modules/@ergonode/product-templates/src/components/Grids/ProductTemplatesGrid.vue
  modules/@ergonode/product-templates/src/components/Modals/CreateProductTemplateModalForm.vue
  modules/@ergonode/product-templates/src/components/Modals/SectionTemplateModalForm.vue
  modules/@ergonode/product-templates/src/components/SideBars/WidgetsSideBar.vue
  modules/@ergonode/product-templates/src/components/Tabs/ProductTemplateGeneralTab.vue
  modules/@ergonode/product-templates/src/components/Tabs/TemplateDesignerTab.vue
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/product-templates/src/pages/product-templates/_template/_id.vue
  modules/@ergonode/product-templates/src/pages/product-templates/index.vue
  modules/@ergonode/product-templates/src/store/productTemplate/actions.js
Labels: Core

#833 Media interface translation
  modules/@ergonode/media/src/components/Buttons/LinkRelationButton.vue
  modules/@ergonode/media/src/components/Buttons/RemoveResourceButton.vue
  modules/@ergonode/media/src/components/Buttons/UpdateResourceTranslationButton.vue
  modules/@ergonode/media/src/components/Buttons/UploadResourcesButton.vue
  modules/@ergonode/media/src/components/Forms/ResourceForm.vue
  modules/@ergonode/media/src/components/Forms/ResourceRelationsForm.vue
  modules/@ergonode/media/src/components/Forms/ResourceTranslationForm.vue
  modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
  modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
  modules/@ergonode/media/src/components/Grids/MediaGrid.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
  modules/@ergonode/media/src/components/Modal/ModalMediaTabBar.vue
  modules/@ergonode/media/src/components/Tabs/ResourceGeneralTab.vue
  modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
  modules/@ergonode/media/src/locales/en_GB.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/media/src/pages/media/_resource/_id.vue
  modules/@ergonode/media/src/pages/media/index.vue
  modules/@ergonode/product-statuses/src/pages/product-statuses/_status/_id.vue
  modules/@ergonode/segments/src/pages/segments/_segment/_id.vue
  modules/@ergonode/status-transitions/src/locales/pl_PL.json
Labels: Media

#835 Import interface translations
  modules/@ergonode/import/src/components/Buttons/CreateImportButton.vue
  modules/@ergonode/import/src/components/Buttons/CreateImportProfileButton.vue
  modules/@ergonode/import/src/components/Buttons/RemoveImportButton.vue
  modules/@ergonode/import/src/components/Buttons/UploadImportButton.vue
  modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
  modules/@ergonode/import/src/components/Grids/ImportProfileHistoryGrid.vue
  modules/@ergonode/import/src/components/Grids/ImportProfilesGrid.vue
  modules/@ergonode/import/src/components/Modals/CreateImportProfileModalForm.vue
  modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
  modules/@ergonode/import/src/components/Modals/UploadImportFileModalForm.vue
  modules/@ergonode/import/src/components/Tabs/ImportProfileGeneralTab.vue
  modules/@ergonode/import/src/locales/en_GB.json
  modules/@ergonode/import/src/locales/pl_PL.json
  modules/@ergonode/import/src/pages/imports/_import/_id.vue
  modules/@ergonode/import/src/pages/imports/index.vue
  modules/@ergonode/import/src/store/import/actions.js
Labels: Core

#836 Channel interface translation
  modules/@ergonode/channels/src/components/Buttons/CreateChannelButton.vue
  modules/@ergonode/channels/src/components/Buttons/CreateExportButton.vue
  modules/@ergonode/channels/src/components/Buttons/DownloadExportFileButton.vue
  modules/@ergonode/channels/src/components/Buttons/RemoveChannelButton.vue
  modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
  modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
  modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
  modules/@ergonode/channels/src/components/Grids/ChannelsGrid.vue
  modules/@ergonode/channels/src/components/Grids/ExportDetailsGrid.vue
  modules/@ergonode/channels/src/components/Modals/CreateChannelModalForm.vue
  modules/@ergonode/channels/src/components/Modals/ExportDetailsModalGrid.vue
  modules/@ergonode/channels/src/components/Tabs/ChannelGeneralTab.vue
  modules/@ergonode/channels/src/components/Tabs/ChannelSchedulerTab.vue
  modules/@ergonode/channels/src/locales/en_GB.json
  modules/@ergonode/channels/src/locales/pl_PL.json
  modules/@ergonode/channels/src/pages/channels/_channel/_id.vue
  modules/@ergonode/channels/src/pages/channels/index.vue
  modules/@ergonode/channels/src/store/channel/actions.js
  modules/@ergonode/import/src/store/import/actions.js
  modules/@ergonode/segments/src/store/segment/actions.js
Labels: Channels

#839 Core interface translation
  modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
  modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
  modules/@ergonode/core/src/components/Tabs/UnitGeneralTab.vue
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/core/src/plugins/axios.js
  modules/@ergonode/ui/src/components/ColorPicker/ColorPicker.vue
  modules/@ergonode/ui/src/components/Grid/Modals/GridSettingsModalForm.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Footers/SelectDropdownApplyFooter.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/Footers/SelectDropdownFooter.vue
Labels: Core

#838 Condition interface translation
  modules/@ergonode/conditions/src/components/SideBars/ConditionsSideBar.vue
  modules/@ergonode/conditions/src/locales/en_GB.json
  modules/@ergonode/conditions/src/locales/pl_PL.json
Labels: Core

#842 Horizontal tabbars resposivity
  modules/@ergonode/core/src/mixins/modals/gridModalMixin.js
  modules/@ergonode/import/src/locales/pl_PL.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBar.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarContent.vue
  modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarItems.vue
  modules/@ergonode/ui/src/components/TabBar/Routing/HorizontalRoutingTabBar.vue
  modules/@ergonode/ui/src/components/TabBar/Routing/HorizontalRoutingTabBarContent.vue
  modules/@ergonode/ui/src/components/TabBar/TabBarItemSlider.vue
Labels: Core, UI Components, bug

#847 bugfix: template icon for gallery and file
  README.md
  modules/@ergonode/attributes/src/config/imports.js
  modules/@ergonode/media/src/components/Icons/IconImage.vue
  modules/@ergonode/media/src/config/extends.js
  modules/@ergonode/media/src/config/imports.js
Labels: Template designer

#850 Add support for product relation presentation cell
  modules/@ergonode/media/src/config/imports.js
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
  modules/@ergonode/products/src/config/extends.js
  modules/@ergonode/products/src/config/imports.js
  modules/@ergonode/products/src/extends/ui/componnets/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
  modules/@ergonode/products/src/extends/ui/componnets/Grid/Layout/Table/Cells/Data/GridLabelDataCell.vue
  modules/@ergonode/products/src/extends/ui/componnets/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
  modules/@ergonode/products/src/extends/ui/componnets/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
  modules/@ergonode/products/src/extends/ui/componnets/Grid/Layout/Table/Cells/Presentation/GridLabelPresentationCell.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/roles/src/config/imports.js
  modules/@ergonode/roles/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridPrivilegeNameHintDataCell.vue
  modules/@ergonode/roles/src/extends/ui/components/Grid/Layout/Table/Columns/GridPrivilegeRowCheckColumn.vue
  modules/@ergonode/users/src/config/imports.js
  modules/@ergonode/users/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridLanguageNameHintDataCell.vue
  modules/@ergonode/users/src/extends/ui/components/Grid/Layout/Table/Columns/GridLanguageRowCheckColumn.vue
Labels: Core, Grid, Product, UI Components

#853 Polish interface translations improvement
  modules/@ergonode/attribute-groups/src/locales/pl_PL.json
  modules/@ergonode/attributes/src/locales/pl_PL.json
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/category-trees/src/locales/pl_PL.json
  modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
  modules/@ergonode/channels/src/locales/pl_PL.json
  modules/@ergonode/collections/src/locales/pl_PL.json
  modules/@ergonode/comments/src/locales/pl_PL.json
  modules/@ergonode/conditions/src/config/extends.js
  modules/@ergonode/conditions/src/locales/en_GB.json
  modules/@ergonode/conditions/src/locales/pl_PL.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/product-templates/src/config/extends.js
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/products/src/components/Modals/RestoreProductAttributesModalForm.vue
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/roles/src/locales/pl_PL.json
  modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/segments/src/locales/en_GB.json
  modules/@ergonode/segments/src/locales/pl_PL.json
  modules/@ergonode/status-transitions/src/locales/pl_PL.json
  modules/@ergonode/users/src/locales/pl_PL.json
Labels: Core, bug

#854 Polish interface translations improvement
  modules/@ergonode/attribute-groups/src/locales/pl_PL.json
  modules/@ergonode/attributes/src/locales/pl_PL.json
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/category-trees/src/locales/pl_PL.json
  modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
  modules/@ergonode/channels/src/locales/pl_PL.json
  modules/@ergonode/collections/src/locales/pl_PL.json
  modules/@ergonode/comments/src/locales/pl_PL.json
  modules/@ergonode/conditions/src/config/extends.js
  modules/@ergonode/conditions/src/locales/en_GB.json
  modules/@ergonode/conditions/src/locales/pl_PL.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/product-templates/src/config/extends.js
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/products/src/components/Modals/RestoreProductAttributesModalForm.vue
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/roles/src/locales/pl_PL.json
  modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/segments/src/locales/en_GB.json
  modules/@ergonode/segments/src/locales/pl_PL.json
  modules/@ergonode/status-transitions/src/locales/pl_PL.json
  modules/@ergonode/users/src/locales/pl_PL.json
Labels: Core, bug

#857 bugfix: role update action fix
  modules/@ergonode/roles/src/store/role/actions.js
Labels: Roles, bug

#856 bugfix: role default update property
  modules/@ergonode/roles/src/store/role/actions.js
Labels: Roles, bug

#858 Add batch action product relation form component
  modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeProductRelationFormField.vue
Labels: Attribute, Batch actions, Core

#852 test: e2e for roles
  cypress/integration/9:roles/1:create.feature
  cypress/integration/9:roles/1:create/index.test.js
  cypress/integration/9:roles/2:read.feature
  cypress/integration/9:roles/2:read/index.test.js
  cypress/integration/9:roles/3:update.feature
  cypress/integration/9:roles/3:update/index.test.js
  cypress/integration/9:roles/4:delete.feature
  cypress/integration/9:roles/4:delete/index.test.js
  cypress/integration/common/inputs.test.js
  cypress/models/navigation.js
  modules/@ergonode/roles/src/components/Buttons/CreateRoleButton.vue
  modules/@ergonode/roles/src/components/Buttons/RemoveRoleButton.vue
  modules/@ergonode/roles/src/components/Forms/UserRoleForm.vue
Labels: tests

#860 Add sorting to the media grid
  modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
Labels: Media, bug

#861 Add sorting to the media grid
  modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
Labels: Media, bug

#863 Interface translations template crash
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/categories/src/config/extends.js
  modules/@ergonode/category-trees/src/config/extends.js
  modules/@ergonode/product-batch-actions/src/config/extends.js
Labels: bug

#866 Incorrect method call - i18n
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/categories/src/config/extends.js
  modules/@ergonode/category-trees/src/config/extends.js
  modules/@ergonode/conditions/src/config/extends.js
  modules/@ergonode/product-batch-actions/src/config/extends.js
  modules/@ergonode/product-templates/src/config/extends.js
Labels: bug

#865 App translation crash
  modules/@ergonode/attributes/src/config/extends.js
  modules/@ergonode/categories/src/config/extends.js
  modules/@ergonode/category-trees/src/config/extends.js
  modules/@ergonode/conditions/src/config/extends.js
  modules/@ergonode/product-batch-actions/src/config/extends.js
  modules/@ergonode/product-templates/src/config/extends.js
Labels: bug

#868 tets: add user e2e tests
  cypress/integration/10:users/1:create.feature
  cypress/integration/10:users/1:create/index.test.js
  cypress/integration/10:users/2:read.feature
  cypress/integration/10:users/2:read/index.test.js
  cypress/integration/10:users/3:update.feature
  cypress/integration/10:users/3:update/index.test.js
  cypress/integration/10:users/4:delete.feature
  cypress/integration/10:users/4:delete/index.test.js
  cypress/integration/common/actions.test.js
  cypress/integration/common/inputs.test.js
  cypress/models/index.js
  cypress/models/navigation.js
  modules/@ergonode/roles/src/extends/user/components/Forms/UserFormRole.vue
  modules/@ergonode/users/src/components/Buttons/CreateUserButton.vue
  modules/@ergonode/users/src/components/Buttons/RemoveUserButton.vue
  modules/@ergonode/users/src/components/Forms/UserForm.vue
  package-lock.json
  package.json
Labels: Users, tests

#875 Present columns in correct order
  modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Labels: Core, Product, UI Components, feature

#874 Correct default status value mapping
  modules/@ergonode/product-statuses/src/store/productStatus/actions.js
Labels: bug

#873 Correct default status value mapping
  modules/@ergonode/product-statuses/src/store/productStatus/actions.js
Labels: bug

#871 Missing polish translations
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/category-trees/src/locales/pl_PL.json
  modules/@ergonode/collections/src/components/Buttons/UpdateCollectionProductsVisibilityButton.vue
  modules/@ergonode/collections/src/locales/en_GB.json
  modules/@ergonode/collections/src/locales/pl_PL.json
  modules/@ergonode/core/src/components/Buttons/CreateUnitButton.vue
  modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
  modules/@ergonode/core/src/components/DropZones/RemoveElementDropZone.vue
  modules/@ergonode/core/src/components/Forms/UnitForm.vue
  modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
  modules/@ergonode/core/src/components/SideBars/LanguagesSideBar.vue
  modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
  modules/@ergonode/core/src/config/extends.js
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/core/src/store/core/actions.js
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/users/src/locales/pl_PL.json
Labels: bug

#870 Missing polish translations
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/category-trees/src/locales/pl_PL.json
  modules/@ergonode/collections/src/components/Buttons/UpdateCollectionProductsVisibilityButton.vue
  modules/@ergonode/collections/src/locales/en_GB.json
  modules/@ergonode/collections/src/locales/pl_PL.json
  modules/@ergonode/core/src/components/Buttons/CreateUnitButton.vue
  modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
  modules/@ergonode/core/src/components/DropZones/RemoveElementDropZone.vue
  modules/@ergonode/core/src/components/Forms/UnitForm.vue
  modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
  modules/@ergonode/core/src/components/SideBars/LanguagesSideBar.vue
  modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
  modules/@ergonode/core/src/config/extends.js
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/core/src/store/core/actions.js
  modules/@ergonode/product-templates/src/locales/en_GB.json
  modules/@ergonode/product-templates/src/locales/pl_PL.json
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
  modules/@ergonode/users/src/locales/pl_PL.json
Labels: bug

#876 Improve column order
  modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Labels: bug

#878 Polish translations improvement
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/core/src/pages/settings/index.vue
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: bug

#877 Polish translations
  modules/@ergonode/categories/src/locales/pl_PL.json
  modules/@ergonode/core/src/locales/en_GB.json
  modules/@ergonode/core/src/locales/pl_PL.json
  modules/@ergonode/core/src/pages/settings/index.vue
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: bug
