Repository ergonode/frontend, pull requests merged in 2021-07, with the labels that each got.

#942 Translations mapping
  modules/@ergonode/attributes/src/extends/attribute/methods/index.js
Labels: bug

#944 Correct status transition translation spelling
  modules/@ergonode/workflow/src/locales/en_GB.json
Labels: Workflow, bug

#945 Workflow designer left padding
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Labels: Workflow, bug

#946 bugfix: create status without save
  modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowStatusButton.vue
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionFab.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/locales/en_GB.json
  modules/@ergonode/workflow/src/locales/pl_PL.json
  modules/@ergonode/workflow/src/models/workflowDesigner/index.js
Labels: Workflow, bug

#943 Unifying input architecture
  modules/@ergonode/categories/src/components/Selects/CategorySelect.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
  modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
  modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
  modules/@ergonode/products/src/components/ProductCarousel/ProductCarousel.vue
  modules/@ergonode/products/src/components/ProductCarousel/ProductCarouselImage.vue
  modules/@ergonode/ui/src/components/Carousel/Carousel.vue
  modules/@ergonode/ui/src/components/Carousel/CarouselItem.vue
  modules/@ergonode/ui/src/components/Carousel/CarouselPageInformation.vue
  modules/@ergonode/ui/src/components/Carousel/CarouselPagination.vue
  modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
  modules/@ergonode/ui/src/components/ColorPicker/ColorPicker.vue
  modules/@ergonode/ui/src/components/Icons/Actions/IconRefresh.vue
  modules/@ergonode/ui/src/components/ImageCarousel/ImageCarousel.vue
  modules/@ergonode/ui/src/components/ImageCarousel/ImageCarouselImage.vue
  modules/@ergonode/ui/src/components/Input/InputController.vue
  modules/@ergonode/ui/src/components/Input/InputImageController.vue
  modules/@ergonode/ui/src/components/Input/InputLabel.vue
  modules/@ergonode/ui/src/components/Input/InputSelectValue.vue
  modules/@ergonode/ui/src/components/Input/InputSolidStyle.vue
  modules/@ergonode/ui/src/components/Input/InputUnderlineStyle.vue
  modules/@ergonode/ui/src/components/Input/InputUploadPlaceholder.vue
  modules/@ergonode/ui/src/components/Input/InputUploadSpinner.vue
  modules/@ergonode/ui/src/components/Preloader/Preloader.vue
  modules/@ergonode/ui/src/components/RichTextEditor/MenuBubble/RichTextEditorMenuBubble.vue
  modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
  modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
  modules/@ergonode/ui/src/components/Select/Select.vue
  modules/@ergonode/ui/src/components/TextArea/TextArea.vue
  modules/@ergonode/ui/src/components/TextField/TextField.vue
  modules/@ergonode/ui/src/components/UploadFile/UploadFile.vue
  modules/@ergonode/workflow/src/components/Badges/WorkflowStatusBadge.vue
  modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
  modules/@ergonode/workflow/src/components/Inputs/ColorPickerInputValue.vue
  modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
Labels: Architecture, Core, UI Components, feature

#948 Add missing status widget translations
  modules/@ergonode/dashboard/src/components/Widgets/StatusesWidget.vue
  modules/@ergonode/dashboard/src/locales/en_GB.json
  modules/@ergonode/dashboard/src/locales/pl_PL.json
Labels: bug

#947 Product relations grid crash on column removal
  modules/@ergonode/core/src/services/grid/postGridData.service.js
  modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Labels: bug

#950 Hide table layout activator
  modules/@ergonode/ui/src/components/Grid/Header/GridHeader.vue
Labels: UI Components, feature

#949 Hover status workflow column header
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerEditStatusLink.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
  modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
Labels: bug

#951 Translations and overflowing avatar
  modules/@ergonode/import/src/locales/pl_PL.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/ui/src/components/Icons/Icon.vue
  modules/@ergonode/ui/src/components/TextField/TextFieldSuffix.vue
  modules/@ergonode/ui/src/components/UploadFile/UploadFile.vue
  package-lock.json
  package.json
Labels: bug

#952 Er 1399/transitions edit button
  modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowStatusButton.vue
  modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionFab.vue
  modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/locales/en_GB.json
  modules/@ergonode/workflow/src/locales/pl_PL.json
  modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
  modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
Labels: Workflow, bug

#953 Grid layout visual improvement
  modules/@ergonode/core/src/defaults/grid/index.js
  modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
  modules/@ergonode/products/src/config/extends.js
  modules/@ergonode/products/src/config/imports.js
  modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Presentation/GridImagePresentationCell.vue
  modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Labels: UI Components, feature

#954 Update vue-windowing dependency
  package-lock.json
  package.json
Labels: bug

#955 Transition tooltip title
  modules/@ergonode/workflow/src/locales/en_GB.json
  modules/@ergonode/workflow/src/locales/pl_PL.json
Labels: Workflow, bug

#956 Polish interface translations
  modules/@ergonode/attributes/src/locales/pl_PL.json
  modules/@ergonode/authentication/src/locales/pl_PL.json
  modules/@ergonode/channels/src/locales/pl_PL.json
  modules/@ergonode/collections/src/locales/pl_PL.json
  modules/@ergonode/comments/src/locales/pl_PL.json
  modules/@ergonode/import/src/locales/pl_PL.json
  modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/users/src/locales/pl_PL.json
Labels: bug

#959 Include column visibility in detecting column
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/ui/src/components/Grid/Grid.vue
Labels: bug

#958 Remove unused fonts
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-Black.woff2
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-BlackItalic.woff2
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-ExtraBold.woff2
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-ExtraBoldItalic.woff2
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-Italic.woff2
  modules/@ergonode/ui/src/assets/fonts/intern/Inter-UI-Regular.woff2
  modules/@ergonode/ui/src/assets/scss/font-inter-ui.scss
Labels: performance

#957 Missing user avatar
  modules/@ergonode/dashboard/src/components/WelcomeUser/WelcomeUser.vue
  modules/@ergonode/ui/src/components/LazyImage/LazyImage.vue
Labels: bug

#960 bugfix: edit transition not found
  modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
  modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
  modules/@ergonode/workflow/src/locales/en_GB.json
  modules/@ergonode/workflow/src/locales/pl_PL.json
Labels: Workflow, bug

#964 bugfix: wrong import
  modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
  nuxt.config.js
Labels: bug

#965 wrong import
  modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
  nuxt.config.js
Labels: bug

#971 bugfix: change product id for validation
  modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
  modules/@ergonode/products/src/store/product/actions.js
Labels: Product, bug

#977 Tooltip component
  modules/@ergonode/core/src/defaults/theme/index.js
  modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
  modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
Labels: UI Components, feature

#979 Encapsulating condition set item parameters
  modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItem.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerMultiSelectItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNoTypeItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNumericItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerSelectItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerTextItemParameter.vue
  modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerUnitItemParameter.vue
  modules/@ergonode/conditions/src/locales/en_GB.json
  modules/@ergonode/conditions/src/locales/pl_PL.json
  modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormNoTypeField.vue
Labels: feature

#983 Extending grid columns
  modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Labels: bug

#985 Migrate uuid generation
  modules/@ergonode/ui/src/components/Input/InputUUIDProvider.vue
Labels: bug

#984 Add translations for resource metadata
  modules/@ergonode/core/src/models/stringWrapper.js
  modules/@ergonode/media/src/locales/en_GB.json
  modules/@ergonode/media/src/locales/pl_PL.json
  modules/@ergonode/media/src/store/media/actions.js
Labels: feature

#986 Add missing method for string transforming
  modules/@ergonode/media/src/store/media/actions.js
Labels: bug

#988 Greyish colors update
  modules/@ergonode/ui/src/assets/scss/_variables/_colors.scss
Labels: Core, feature

#990 Move create comment button to placeholder
  modules/@ergonode/comments/src/components/Forms/CommentsForm.vue
  modules/@ergonode/comments/src/components/List/CommentsList.vue
Labels: Product, bug

#992 Removed plus icon
  modules/@ergonode/channels/src/components/Buttons/CreateExportButton.vue
  modules/@ergonode/import/src/components/Buttons/CreateImportButton.vue
Labels: feature

#994 Add tooltip to product variant binding attributes, improve fluid positioning
  modules/@ergonode/products/src/extends/components/Forms/ProductAttributesBindingForm.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/ui/src/components/Form/Section/FormListSection.vue
  modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
Labels: bug, feature

#1004 Destroy tooltip when title is empty
  modules/@ergonode/products/src/locales/pl_PL.json
  modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
Labels: UI Components, bug

#999 Show adding column dropzone only for GridTableLayout
  modules/@ergonode/ui/src/components/Grid/Grid.vue
Labels: bug

#1003 Unify product collection item
  modules/@ergonode/collections/src/extends/product/components/Collection/ProductCollectionItem.vue
  modules/@ergonode/collections/src/extends/product/components/ExpandingCollection/ExpandingCollection.vue
  modules/@ergonode/collections/src/extends/product/components/Tabs/ProductCollectionTab.vue
Labels: Product, feature

#1001 Add searching and sorting for LanguageSelect
  modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
  modules/@ergonode/users/src/components/Forms/UserForm.vue
Labels: feature

#996 Add placeholder to product
  modules/@ergonode/product-templates/src/config/extends.js
  modules/@ergonode/product-templates/src/config/imports.js
  modules/@ergonode/product-templates/src/extends/components/Buttons/EditProductTemplateButton.vue
  modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
  modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
  modules/@ergonode/products/src/locales/en_GB.json
  modules/@ergonode/products/src/locales/pl_PL.json
Labels: Product, feature
